version: '2'

services:

  myproject:
    build: .
    container_name: myproject_in_compose
    ports:
      - 8000:8000
    expose:
      - 8000
    links:
      - database:database
    depends_on:
      - database
    command: sh ./wait-for-it.sh db:6603

  database:
    image: mysql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_TCP_PORT: 6604
    ports:
      - "6604:6604"
    expose:
      - "6604"
    volumes:
      # make ./db_dump/dump.sql
      # or get it from ftp://fsm.dev.local/Storage/TeenSafe/TSiPhoneMonitor
      - ./db_dump:/docker-entrypoint-initdb.d
